### ISSUE TITLE
Add: pre commit testing

### ISSUE THREAD

**Issue by 21st-centuryman** [teeny-kth/teenygrad#41]
I think adding a small pre commit test that will run when we commit our code. it should probably look like the following:

```yml
repos:
  - repo: local
    hooks:
      - id: sz
        name: line counter
        entry: env cargo test sz
        language: system
        always_run: true
        pass_filenames: false
```

If we are running out of lines we should create issues, make new branches, compress our files, and PR.

Or we change the line counter.

 If we go git worktrees it should be easy to just add a branch and continue.
